#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

set -x

cd /
rm /init
EXEC=/init

exec >>/boot.txt 2>&1

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t ext4 /dev/block/mmcblk0p15 /cache
mount -t vfat /dev/block/mmcblk0p10 /efs

#busybox date segfaults? so yeah.
busybox cat /sys/devices/platform/s3c2410-rtc/rtc/rtc1/date
busybox cat /sys/devices/platform/s3c2410-rtc/rtc/rtc1/time

image=/stage1/boot.cpio

# Set the wifi mac addr
if test -e /efs/imei/.nvmac.info; then
	busybox printf "$(busybox cat /efs/imei/.nvmac.info)" > /sys/module/mach_venturi/parameters/wlan_mac
else
	busybox printf "00:00:00:00:00:00" > /sys/module/mach_venturi/parameters/wlan_mac
fi

if test -e /efs/buyer_code.dat; then
	# Set the buyer code (registers input keys)
	busybox printf "$(busybox cat /efs/buyer_code.dat)" > /sys/module/mach_venturi/parameters/variant_code

	# Set the buyer code (init input/touchscreen driver)
	busybox printf "$(busybox cat /efs/buyer_code.dat)" > /sys/module/cytma340/parameters/variant_code
else
	busybox printf "ERR" > /sys/module/mach_venturi/parameters/variant_code
	busybox printf "ERR" > /sys/module/cytma340/parameters/variant_code
fi

# Reboot check
if test $(busybox cat /sys/module/param/parameters/reboot_mode) == 2 ; then
	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

# Recovery check
if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then

	#load custom recovery ramdisk if it's there
	if test -e /cache/custom_recovery/ramdisk-recovery.cpio ; then
		image=/cache/custom_recovery/ramdisk-recovery.cpio
	else
		image=/stage1/recovery.cpio
	fi

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting

	rm -rf /cache/.startrecovery
else
	#load custom ramdisk if it's there
	if test -e /cache/custom_ramdisk/ramdisk.cpio ; then
		image=/cache/custom_ramdisk/ramdisk.cpio
	fi

fi

cpio -i < ${image}

umount /cache
rm -rf /cache

busybox cat /sys/class/power_supply/battery/charging_mode_booting

# Charging mode check
if test $(busybox cat /sys/class/power_supply/battery/charging_mode_booting) == 1 ; then
	# low power mode
	cp -f lpm.rc init.venturi.rc
fi

umount /sys
umount /proc
umount /efs

mount -t vfat /dev/block/mmcblk0p17 /emmc
busybox cat /boot.txt >> /emmc/boot.txt
umount /emmc

rm -rf /dev/* /stage1 /emmc /efs

export PATH="${_PATH}"

exec $EXEC
